# Local DEV database
services:
    eventos_y_tickets_dev_db:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=eventosytickets
            - MYSQL_USER=eventosytickets
            - MYSQL_PASSWORD=eventosytickets
        volumes:
            - eyt_db_volume:/var/lib/mysql

volumes:
    eyt_db_volume: {}
