from common.constants.order_statuses import DECLINED, FAILED


PAYPAL_COMPLETED = "COMPLETED"
PAYER_ACTION_REQUIRED = "PAYER_ACTION_REQUIRED"
APPROVED = "APPROVED"

JOURNAL_REQUEST = "REQUEST"
JOURNAL_RESPONSE = "RESPONSE"
JOURNAL_FAILURE = "FAILURE"
JOURNAL_CAPTURE_REQUEST = "CAPTURE_REQUEST"
JOURNAL_CAPTURE_RESPONSE = "CAPTURE_RESPONSE"
JOURNAL_CAPTURE_FAILURE = "CAPTURE_FAILURE"

# Errors
UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
TRANSACTION_REFUSED = "TRANSACTION_REFUSED"
CARD_EXPIRED = "CARD_EXPIRED"
UNKNOWN = "UNKNOWN"
INTERNAL_ERROR = "INTERNAL_ERROR"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

ORDER_STATUS_BY_PAYPAL_ERROR = {
    TRANSACTION_REFUSED: DECLINED,
    CARD_EXPIRED: FAILED,
    UNKNOWN: FAILED,
}
