from common.constants.order_statuses import DECLINED, FAILED


PAYPAL_COMPLETED = "COMPLETED"

JOURNAL_REQUEST = "REQUEST"
JOURNAL_RESPONSE = "RESPONSE"
JOURNAL_FAILURE = "FAILURE"
JOURNAL_REDIRECT_RESPONSE = "REDIRECT_RESPONSE"

# Errors
UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
TRANSACTION_REFUSED = "TRANSACTION_REFUSED"
CARD_EXPIRED = "CARD_EXPIRED"
UNKNOWN = "UNKNOWN"

ORDER_STATUS_BY_PAYPAL_ERROR = {
    TRANSACTION_REFUSED: DECLINED,
    CARD_EXPIRED: FAILED,
    UNKNOWN: FAILED,
}
