DRAFT_ID = 1
PUBLISHED_ID = 2
FINALIZED_ID = 3

DRAFT = "DRAFT"
PUBLISHED = "PUBLISHED"
FINALIZED = "FINALIZED"

EVENT_STATUS_ID_BY_NAME = {
    DRAFT: DRAFT_ID,
    PUBLISHED: PUBLISHED_ID,
    FINALIZED: FINALIZED_ID,
}

EVENT_STATUS_NAME_BY_ID = {
    DRAFT_ID: DRAFT,
    PUBLISHED_ID: PUBLISHED,
    FINALIZED_ID: FINALIZED,
}
