CREATED = "CREATED"
COMPLETED = "COMPLETED"
PENDING = "PENDING"
DECLINED = "DECLINED"
FAILED = "FAILED"
ABANDONED = "ABANDONED"
REFUNDED = "REFUNDED"

CREATED_ID = 1
COMPLETED_ID = 2
PENDING_ID = 3
DECLINED_ID = 4
FAILED_ID = 5
ABANDONED_ID = 6
REFUNDED_ID = 7

ORDER_STATUS_ID_BY_NAME = {
    CREATED: CREATED_ID,
    COMPLETED: COMPLETED_ID,
    PENDING: PENDING_ID,
    DECLINED: DECLINED_ID,
    FAILED: FAILED_ID,
    ABANDONED: ABANDONED_ID,
    REFUNDED: REFUNDED_ID,
}

ORDER_STATUS_NAME_BY_ID = {
    CREATED_ID: CREATED,
    COMPLETED_ID: COMPLETED,
    PENDING_ID: PENDING,
    DECLINED_ID: DECLINED,
    FAILED_ID: FAILED,
    ABANDONED_ID: ABANDONED,
    REFUNDED_ID: REFUNDED,
}
