CREATED = "CREATED"
COMPLETED = "COMPLETED"
PENDING = "PENDING"
DECLINED = "DECLINED"
FAILED = "FAILED"
ABANDONED = "ABANDONED"
REFUNDED = "REFUNDED"

CREATED_ID = 1
COMPLETED_ID = 2
PENDING_ID = 3
DECLINED_ID = 4
FAILED_ID = 5
ABANDONED_ID = 6
REFUNDED_ID = 7
