CREDIT = "CREDIT"
PAYPAL = "PAYPAL"

CREDIT_ID = 1
PAYPAL_ID = 2

PAYMENT_METHOD_ID_BY_NAME = {CREDIT: CREDIT_ID, PAYPAL: PAYPAL_ID}

PAYMENT_METHOD_NAME_BY_ID = {CREDIT_ID: CREDIT, PAYPAL_ID: PAYPAL}

SUPPORTED_PAYMENT_METHODS = [CREDIT, PAYPAL]
