CREDIT = "CREDIT"
PAYPAL = "PAYPAL"
FREE = "FREE"

CREDIT_ID = 1
PAYPAL_ID = 2
FREE_ID = 3

PAYMENT_METHOD_ID_BY_NAME = {CREDIT: CREDIT_ID, PAYPAL: PAYPAL_ID, FREE: FREE_ID}

PAYMENT_METHOD_NAME_BY_ID = {CREDIT_ID: CREDIT, PAYPAL_ID: PAYPAL, FREE_ID: FREE}

SUPPORTED_PAYMENT_METHODS = [CREDIT, PAYPAL, FREE]
