name: Terraform Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy-prod:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set Terraform token and backend.tf
              env:
                  TF_TOKEN_app_terraform_io: ${{secrets.TFE_TOKEN}}
              run: |
                  cat >backend.tf <<EOL
                  terraform {
                   backend "remote" {
                           hostname     = "app.terraform.io"
                           organization = "EventosyTickets"

                           workspaces {
                           name = "eventos-y-tickets-backend-prod"
                           }
                       }
                   }
                   EOL
            - name: cat
              run: cat backend.tf
            - name: terraform init
              run: terraform init
